# Generated by Django 2.0 on 2019-11-24 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('generation', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('civil_status', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('highest_educational_attainment', models.CharField(max_length=64)),
                ('educational_status', models.CharField(max_length=64)),
                ('tenure', models.CharField(max_length=64)),
                ('employment_status', models.CharField(max_length=64)),
                ('pay_class', models.CharField(max_length=64)),
                ('last_employee_movement', models.CharField(max_length=64)),
                ('latest_performance_rating', models.CharField(max_length=64)),
                ('job_loc', models.CharField(max_length=64)),
                ('rank', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
