# Generated by Django 2.0 on 2019-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='educational_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='generation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highest_educational_attainment',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_loc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_employee_movement',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_performance_rating',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_class',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenure',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
