# Generated by Django 2.0 on 2019-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191124_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tenure',
            field=models.IntegerField(),
        ),
    ]
