# Generated by Django 2.0 on 2019-11-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191124_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='generation',
        ),
    ]
