# Generated by Django 2.0 on 2019-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tenure',
            field=models.FloatField(),
        ),
    ]
