# Generated by Django 2.0 on 2019-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191124_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_unit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
