# Generated by Django 2.0 on 2019-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191124_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
