# Generated by Django 2.0 on 2019-11-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='employee_wwid',
        ),
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='is_data_change',
        ),
        migrations.RemoveField(
            model_name='jobchangerequest',
            name='is_employee_change',
        ),
    ]
